### PR TITLE
Added the Shelly Plus and Pro relay devices

### PR DESCRIPTION
**Pull request by TheKilroy**
The graphics for the Shelly Pro Line fits the sizes for the cabinet graphics for the circuit breakers so that they will integrate into the detail picture.

### CODE REVIEW

**Comment by scorpio810** [comment]
Tanks, you don't want to add to master ?

**Comment by TheKilroy** [comment]
I have not used github a lot and I am more a newbie to it. So maybe it might be worth that I remove the "master" branch in my repo. Then both repos have only the "main" branch.

**Comment by scorpio810** [comment]
sorry  when I say that I say off master it is the deposit of the official collection
https://github.com/qelectrotech/qelectrotech-source-mirror

**Comment by TheKilroy** [comment]
OK, thank you for your explanation. I thought that this repo holds old elements not been in the "qelectrotech" repo anymore and gets new user contributed elements. The program looks so amazing good and I am still a newbie generating new elements as well as using github. I still think there are many more things to do with the elements i.e. translation, text, etc. that they are not yet complete enough to be integrated into the "master" repo.
I am open to any new information or discussion about it. Anyway a great job done with that piece of software,

**Comment by scorpio810** [comment]
https://git.tuxfamily.org/qet/qet.git/commit/?id=fe66caf5ac08fe9b12a67070b025c95221f2c36f

**Pull request merged**
